### ISSUE TITLE
Plugin maintenance

### ISSUE THREAD

**Issue by vladshcherbin** [vimeo/rollup-plugin-bundle-size#10]
Hey 👋 

I've used this plugin in a few projects and met some limitations, latest one with using `output.dir` instead of `output.file` which results in an error.

I see this repo has a few issues and PRs. Instead of creating another same purpose package I'd like to help with support for this one. Previously I did same thing for other common rollup plugins and maintain a few of them.

What do you think?

**Comment by vladshcherbin** [comment]
@luwes after email conversation from npm, are you willing to accept PRs and update this package?

Would be happy to see your reply, even if you say "no", just to be clear before creating another package for same thing.

Thanks

**Comment by fisherinnovation** [comment]
@vladshcherbin We will be happy to review and include approved PR's into this repo. Thanks for your interest!
